[package]
name = "paillier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = { version = "0.3.0", features = ["rand"] }
num-primes = "0.3.0"
num-bigint = "0.2.6"
rand = "0.6.0"